GET http://localhost:3001/dishes
###
GET http://localhost:3001/dishes/6aac7271c4e442b5db1967b0
###
PUT http://localhost:3001/dishes/6aac7271c4e442b5db1967b0
Content-Type: application/json

  {
    "_id": "6aac7271c4e442b5db1967b0",
    "name": "Sushi",
    "ingredients": [
      "Japanese Rice",
      "Salmon",
      "Nori Seaweed"
    ],
    "price": 24.9,
    "available_sizes": [
      "8 pieces",
      "16 pieces",
      "24 pieces",
      "30 pieces"
    ]
  }

###
POST http://localhost:3001/dishes
Content-Type: application/json

{
    "name": "Mabudofu",
    "ingredients": [
        "tofu", 
        "groudbeef", 
        "spice", 
        "oil"
    ],
    "price": 19.90,
    "available_sizes": [
        "150g", 
        "300g", 
        "450g"
    ]
}

###
DELETE http://localhost:3001/dishes/6aadb1f0634943afcef281be
###